language: node_js
node_js:
  - '8'
env:
  global:
    - secure: >-
        ZxbXZL4KpdP5glVrV1yzuQVupj0UHkdd9EMz+n/Cn2+geCLgaOF82Wd4lKO0xqe4TG78mzrzipA+eO0qpfWZpnitYo9n8eiQYziRyJcEFEW5XEI54bCOfFbkehhOrpeaulfzJrou4NBkELqVN9f6Cqqtjy/8YZmRXS654u7RPU5e1zmiN/NyRds3EvZikhyDqgBABNc1pNHp04MLuPPYmqIQrfR1efBktxlOYHYe5yKPq2qFs5BVFoyd2DhJZlcSrLFGi1DZbFSsmUgmPWxQHu9bV82lgyceJI3PZ6Ttaa+ann+YEn4hd6ZCXtCm9KEBkfZTbdOfRTMXysCzkX2nZJfqcLFdRIQiKFICI4+dugtTndcATFUgMIGNLgYQ8OzEtij+EGbqzePZSqaLX7D7cBoaTnMrmZjqqEcDGUsY5pLb8ltWCLcave9NPSft3dW87dLr0X/ThenpGAO7KcfY48WzgDRduNwG4duGxoaGNP2/t4Nv5U08mS+UA+ffrmquc6ppW0NMRd8Enn0E9+fsdffn0KAudRTArhyzAqmk2c7eDKMAcOjSwLMRjkmu9PSvuRTSc0qe1ZaJfieav33JKhOcGEd07WF8DcpopFTP/8DeAPy+4PW9QB1LkxnCMgfhSsMlv5vyesYCY/QLBUn3SXkhPWaIPv+GDuT/wtatrmw=
install:
  - npm install
script:
  - npm test
  - npm run doc
after_success:
  - git config user.name "Travis-CI"
  - git config user.email "mugifly@github.io"
  - git checkout --orphan gh-pages
  - git rm --cached -rf .
  - cp docs/dimora-client/*.*.*/* . -R
  - git add *.html && git add scripts/ && git add fonts/ && git add styles/
  - git commit -m 'Update documents'
  - >-
    [ "$TRAVIS_BRANCH" == "master" ] && [ $GITHUB_TOKEN ] && git push --quiet
    --force https://$GITHUB_TOKEN@github.com/mugifly/node-dimora-client.git
    gh-pages 2> /dev/null
